APP_NAME_MAP = {
    "msedgewebview2.exe": "Microsoft Edge WebView",
    "msedge.exe": "Microsoft Edge",
    "chrome.exe": "Google Chrome",
    "firefox.exe": "Mozilla Firefox",
    "opera.exe": "Opera",
    "brave.exe": "Brave Browser",
    "vivaldi.exe": "Vivaldi",
    "obsidian.exe": "Obsidian",
    "code.exe": "VS Code",
    "devenv.exe": "Visual Studio",
    "whatsapp.exe": "WhatsApp",
    "whatsapp.root.exe": "WhatsApp",
    "discord.exe": "Discord",
    "spotify.exe": "Spotify",
    "steam.exe": "Steam",
    "epicgameslauncher.exe": "Epic Games",
    "battle.net.exe": "Battle.net",
    "goggalaxy.exe": "GOG Galaxy",
    "notion.exe": "Notion",
    "slack.exe": "Slack",
    "teams.exe": "Microsoft Teams",
    "telegram.exe": "Telegram",
    "zoom.exe": "Zoom",
    "outlook.exe": "Microsoft Outlook",
    "winword.exe": "Microsoft Word",
    "excel.exe": "Microsoft Excel",
    "powerpnt.exe": "Microsoft PowerPoint",
    "onenote.exe": "Microsoft OneNote",
    "explorer.exe": "File Explorer",
    "cmd.exe": "Command Prompt",
    "powershell.exe": "PowerShell",
    "wt.exe": "Windows Terminal",
    "notepad.exe": "Notepad",
    "notepad++.exe": "Notepad++",
    "sublime_text.exe": "Sublime Text",
    "vim.exe": "Vim",
    "nvim.exe": "Neovim",
    "python.exe": "Python",
    "node.exe": "Node.js",
    "npm.cmd": "npm",
    "git.exe": "Git",
    "docker.exe": "Docker",
    "kubectl.exe": "kubectl",
    "code-oss.exe": "VS Code (OSS)",
    "idea64.exe": "IntelliJ IDEA",
    "pycharm64.exe": "PyCharm",
    "webstorm64.exe": "WebStorm",
    "rider64.exe": "Rider",
    "clion64.exe": "CLion",
    "phpstorm64.exe": "PhpStorm",
    "goland64.exe": "GoLand",
    "rubymine64.exe": "RubyMine",
    "datagrip64.exe": "DataGrip",
    "androidstudio64.exe": "Android Studio",
    "unity.exe": "Unity Editor",
    "unityhub.exe": "Unity Hub",
    "blender.exe": "Blender",
    "gimp.exe": "GIMP",
    "photoshop.exe": "Adobe Photoshop",
    "illustrator.exe": "Adobe Illustrator",
    "premiere.exe": "Adobe Premiere Pro",
    "afterfx.exe": "Adobe After Effects",
    "audition.exe": "Adobe Audition",
    "obs64.exe": "OBS Studio",
    "vlc.exe": "VLC Media Player",
    "mpv.exe": "mpv",
    "potplayer.exe": "PotPlayer",
    "foobar2000.exe": "foobar2000",
    "calculator.exe": "Calculator",
    "snippingtool.exe": "Snipping Tool",
    "snipsketch.exe": "Snip & Sketch",
    "mspaint.exe": "Paint",
    "mspaintapp.exe": "Paint",
    "write.exe": "WordPad",
    "regedit.exe": "Registry Editor",
    "taskmgr.exe": "Task Manager",
    "control.exe": "Control Panel",
    "mmc.exe": "Microsoft Management Console",
    "services.msc": "Services",
    "eventvwr.exe": "Event Viewer",
    "compmgmt.exe": "Computer Management",
    "devmgmt.msc": "Device Manager",
    "diskmgmt.msc": "Disk Management",
    "lusrmgr.msc": "Local Users and Groups",
    "gpedit.msc": "Group Policy Editor",
    "secpol.msc": "Local Security Policy",
    "wf.msc": "Windows Firewall",
    "resmon.exe": "Resource Monitor",
    "perfmon.exe": "Performance Monitor",
    "msconfig.exe": "System Configuration",
    "sysdm.cpl": "System Properties",
    "appwiz.cpl": "Programs and Features",
    "desk.cpl": "Display Settings",
    "hdwwiz.cpl": "Device Manager",
    "inetcpl.cpl": "Internet Options",
    "intl.cpl": "Region",
    "joy.cpl": "Game Controllers",
    "main.cpl": "Mouse",
    "mmsys.cpl": "Sound",
    "ncpa.cpl": "Network Connections",
    "powercfg.cpl": "Power Options",
    "telephon.cpl": "Phone and Modem",
    "timedate.cpl": "Date and Time",
    "optionalfeatures.exe": "Optional Features",
    "systempropertiesadvanced.exe": "Advanced System Properties",
    "systempropertiescomputername.exe": "System Properties (Computer Name)",
    "systempropertieshardware.exe": "System Properties (Hardware)",
    "systempropertiesperformance.exe": "Performance Options",
    "systempropertiesprotection.exe": "System Protection",
    "systempropertiesremote.exe": "Remote Settings",
    "conhost.exe": "Console Window Host",
    "csrss.exe": "Client Server Runtime Process",
    "dwm.exe": "Desktop Window Manager",
    "fontdrvhost.exe": "Font Driver Host",
    "lsass.exe": "Local Security Authority",
    "services.exe": "Services Control Manager",
    "smss.exe": "Session Manager",
    "spoolsv.exe": "Print Spooler",
    "svchost.exe": "Service Host",
    "system": "System",
    "taskhost.exe": "Task Host",
    "taskhostw.exe": "Task Host Window",
    "wininit.exe": "Windows Initialization",
    "winlogon.exe": "Windows Logon",
    "sihost.exe": "Shell Infrastructure Host",
    "startmenuexperiencehost.exe": "Start Menu Experience Host",
    "searchapp.exe": "Search App",
    "searchindexer.exe": "Search Indexer",
    "textinputhost.exe": "Text Input Host",
    "osk.exe": "On-Screen Keyboard",
    "narrator.exe": "Narrator",
    "magnify.exe": "Magnifier",
    "atbroker.exe": "Assistive Technology Broker",
    "shellexperiencehost.exe": "Shell Experience Host",
    "startmenuindexer.exe": "Start Menu Indexer",
    "searchprotocolhost.exe": "Search Protocol Host",
    "searchfilterhost.exe": "Search Filter Host",
    "dllhost.exe": "COM Surrogate",
    "runtimebroker.exe": "Runtime Broker",
    "settingssynchost.exe": "Settings Sync Host",
    "smartscreen.exe": "SmartScreen",
    "securityhealthservice.exe": "Windows Security",
    "antimalwareserviceexecutable.exe": "Windows Defender",
    "msmpeng.exe": "Windows Defender",
    "mpsigstub.exe": "Windows Defender",
    "niassist.exe": "NVIDIA Assistant",
    "nvcontainer.exe": "NVIDIA Container",
    "nvtelemetrycontainer.exe": "NVIDIA Telemetry",
    "nvxdsync.exe": "NVIDIA Sync",
    "nvidia.exe": "NVIDIA Settings",
    "nvidiawebhelper.exe": "NVIDIA Web Helper",
    "geforceexperience.exe": "GeForce Experience",
    "gfexperience.exe": "GeForce Experience",
    "nvidia.daemon.exe": "NVIDIA Daemon",
    "nvidia.telemetry.exe": "NVIDIA Telemetry",
    "nvidia.container.exe": "NVIDIA Container",
    "nvidia.overlay.exe": "NVIDIA Overlay",
    "nvidia.share.exe": "NVIDIA Share",
    "nvidia.streamer.exe": "NVIDIA Streamer",
    "nvidia.vgx.exe": "NVIDIA vGPU",
    "nvidia.vgpu.exe": "NVIDIA vGPU",
    "antigravityide.exe": "Antigravity IDE",
    "antigravity ide.exe": "Antigravity IDE",
}


def normalize_app_name(raw_name: str) -> str:
    """Convert executable name to user-friendly name."""
    if not raw_name:
        return "Desconhecido"
    key = raw_name.strip().lower()
    return APP_NAME_MAP.get(key, raw_name.replace(".exe", "").replace(".EXE", "").title())


def normalize_app_list(app_names: list[str]) -> list[str]:
    """Normalize a list of app names."""
    return [normalize_app_name(name) for name in app_names]
